import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.75.0";

const corsHeaders={ "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type" };
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
function normalizePhone(value:unknown){const digits=String(value??"").replace(/\D/g,"");if(digits.length<8||digits.length>15)throw new Error("Numéro de téléphone invalide.");return digits.replace(/^00/,"").replace(/^225(?=\d{8,})/,"").replace(/^0+/,"");}
function randomHex(bytes=16){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return Array.from(a).map(x=>x.toString(16).padStart(2,"0")).join("");}
function randomCode(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(1000+(a[0]%9000));}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function codeHash(code:string,salt:string){const secret=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||"";return sha256(code+":"+salt+":"+secret);}
async function sessionTokenHash(token:string){return sha256(token);}
async function issueSession(supabase:any,clientId:string,req:Request){const raw=randomHex(32)+"."+randomHex(16);const token_hash=await sessionTokenHash(raw);const {error}=await supabase.from("client_portal_sessions").insert({client_id:clientId,token_hash,expires_at:new Date(Date.now()+7*86400000).toISOString(),user_agent:req.headers.get("user-agent")||null,ip_address:req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("x-real-ip")||null});if(error)throw error;return raw;}
async function findClient(supabase:any,phone:string){for(const candidate of [phone,"0"+phone,"225"+phone,phone.slice(-8)]){const {data}=await supabase.from("clients").select("id,telephone,email,nom_complet,compte_actif,statut_global").or(`telephone.eq.${candidate},telephone.ilike.%${candidate.slice(-8)}`).limit(10);const found=(data||[]).find((c:any)=>{try{return normalizePhone(c.telephone)===phone;}catch{return false;}});if(found)return found;}return null;}
serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders});try{
 const body=await req.json();const action=body?.action||"inspect";const phone=normalizePhone(body?.telephone||"");const secret=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default;const supabase=createClient(Deno.env.get("SUPABASE_URL")!,secret);const client=await findClient(supabase,phone);
 if(!client){if(action==="inspect"||action==="demo")return json({success:true,demo:true,needs_access_code_setup:false,access_code:randomCode()});return json({success:false,error:"Compte client introuvable."},404);}
 if(!client.compte_actif||client.statut_global!=="actif")return json({success:false,error:"Votre compte client n'est pas encore activé. Veuillez contacter AgriCapital."},403);
 const {data:access,error:accessError}=await supabase.from("client_portal_access_codes").select("id,locked_until,last_verified_at").eq("client_id",client.id).maybeSingle();if(accessError)throw accessError;
 if(action==="inspect")return json({success:true,demo:false,client_id:client.id,telephone:client.telephone,client_name:client.nom_complet||"Client AgriCapital",needs_access_code_setup:!access,locked_until:access?.locked_until||null});
 if(action==="setup"){if(access)return json({success:false,error:"Un code d'accès existe déjà pour ce compte. Utilisez-le pour vous connecter.",needs_access_code_setup:false},409);const code=String(body?.code||""),confirm=String(body?.confirm_code||"");if(!/^\d{4}$/.test(code)||code!==confirm)return json({success:false,error:"Le code doit contenir exactement 4 chiffres et les deux champs doivent être identiques."},400);const salt=randomHex(16),hash=await codeHash(code,salt);const {error}=await supabase.from("client_portal_access_codes").insert({client_id:client.id,code_hash:hash,code_salt:salt,failed_attempts:0,locked_until:null,set_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(error){if(error.code==="23505")return json({success:false,error:"Un code d'accès vient d'être enregistré pour ce compte. Utilisez-le pour vous connecter.",needs_access_code_setup:false},409);throw error;}const token=await issueSession(supabase,client.id,req);await supabase.from("historique_activites").insert({table_name:"clients",record_id:client.id,action:"PORTAL_ACCESS_CODE_CREATED",details:"Code d'accès portail client à 4 chiffres créé.",ip_address:req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("x-real-ip")||null,user_agent:req.headers.get("user-agent")||"unknown"});return json({success:true,first_connection:true,access_token:token,client_name:client.nom_complet||"Client AgriCapital"});}
 if(action==="login"){const code=String(body?.code||"");if(!/^\d{4}$/.test(code))return json({success:false,error:"Code d'accès invalide."},400);if(!access)return json({success:false,needs_access_code_setup:true},409);if(access.locked_until&&new Date(access.locked_until).getTime()>Date.now())return json({success:false,error:"Trop de tentatives. Veuillez réessayer plus tard.",locked_until:access.locked_until},429);const {data:fullAccess,error:fullAccessError}=await supabase.from("client_portal_access_codes").select("*").eq("client_id",client.id).single();if(fullAccessError||!fullAccess)return json({success:false,error:"Code d'accès indisponible. Réessayez."},409);const expected=await codeHash(code,fullAccess.code_salt);if(expected!==fullAccess.code_hash){const attempts=Number(fullAccess.failed_attempts||0)+1;const lockedUntil=attempts>=5?new Date(Date.now()+15*60000).toISOString():null;await supabase.from("client_portal_access_codes").update({failed_attempts:attempts>=5?0:attempts,locked_until:lockedUntil,updated_at:new Date().toISOString()}).eq("client_id",client.id);return json({success:false,error:lockedUntil?"Trop de tentatives. Réessayez dans 15 minutes.":"Code d'accès incorrect.",locked_until:lockedUntil},401);}await supabase.from("client_portal_access_codes").update({failed_attempts:0,locked_until:null,last_verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("client_id",client.id);return json({success:true,access_token:await issueSession(supabase,client.id,req),client_name:client.nom_complet||"Client AgriCapital"});}
 if(action==="logout"){const token=String(body?.access_token||"");if(token)await supabase.from("client_portal_sessions").update({revoked_at:new Date().toISOString()}).eq("token_hash",await sessionTokenHash(token));return json({success:true});}
 return json({success:false,error:"Action invalide."},400);
}catch(error:any){console.error("portal-access:",error);return json({success:false,error:error?.message||"Erreur serveur."},500);}});
